# Generated by Django 5.1.4 on 2025-01-10 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('height', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='player_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defensive_score', models.IntegerField()),
                ('passing_score', models.IntegerField()),
                ('scoring_score', models.IntegerField()),
                ('iq_score', models.IntegerField()),
                ('final_grade', models.CharField(max_length=2)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.player')),
            ],
        ),
    ]
