# Generated by Django 4.2.7 on 2025-01-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_remove_player_efficiency_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
