# Generated by Django 5.1.4 on 2025-01-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_player_headshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to='player_images/'),
        ),
    ]
